/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnnotationsDisplay {
        "addAnnotation": boolean;
        "annotationText": string;
        "annotations": any;
        "authenticated": boolean;
        "readOnlyMode": boolean;
    }
    interface DataDisplay {
        "annotations": any;
        "authenticated": boolean;
        "readOnlyMode": boolean;
    }
    interface OrcidConnect {
    }
    interface ThroughputSubmit {
    }
    interface ThroughputWidget {
        "additionalType": string;
        "identifier": string;
        "link": any;
        "readOnlyMode": boolean;
    }
}
declare global {
    interface HTMLAnnotationsDisplayElement extends Components.AnnotationsDisplay, HTMLStencilElement {
    }
    var HTMLAnnotationsDisplayElement: {
        prototype: HTMLAnnotationsDisplayElement;
        new (): HTMLAnnotationsDisplayElement;
    };
    interface HTMLDataDisplayElement extends Components.DataDisplay, HTMLStencilElement {
    }
    var HTMLDataDisplayElement: {
        prototype: HTMLDataDisplayElement;
        new (): HTMLDataDisplayElement;
    };
    interface HTMLOrcidConnectElement extends Components.OrcidConnect, HTMLStencilElement {
    }
    var HTMLOrcidConnectElement: {
        prototype: HTMLOrcidConnectElement;
        new (): HTMLOrcidConnectElement;
    };
    interface HTMLThroughputSubmitElement extends Components.ThroughputSubmit, HTMLStencilElement {
    }
    var HTMLThroughputSubmitElement: {
        prototype: HTMLThroughputSubmitElement;
        new (): HTMLThroughputSubmitElement;
    };
    interface HTMLThroughputWidgetElement extends Components.ThroughputWidget, HTMLStencilElement {
    }
    var HTMLThroughputWidgetElement: {
        prototype: HTMLThroughputWidgetElement;
        new (): HTMLThroughputWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "annotations-display": HTMLAnnotationsDisplayElement;
        "data-display": HTMLDataDisplayElement;
        "orcid-connect": HTMLOrcidConnectElement;
        "throughput-submit": HTMLThroughputSubmitElement;
        "throughput-widget": HTMLThroughputWidgetElement;
    }
}
declare namespace LocalJSX {
    interface AnnotationsDisplay {
        "addAnnotation"?: boolean;
        "annotationText"?: string;
        "annotations"?: any;
        "authenticated"?: boolean;
        "readOnlyMode"?: boolean;
    }
    interface DataDisplay {
        "annotations"?: any;
        "authenticated"?: boolean;
        "readOnlyMode"?: boolean;
    }
    interface OrcidConnect {
    }
    interface ThroughputSubmit {
    }
    interface ThroughputWidget {
        "additionalType"?: string;
        "identifier"?: string;
        "link"?: any;
        "readOnlyMode"?: boolean;
    }
    interface IntrinsicElements {
        "annotations-display": AnnotationsDisplay;
        "data-display": DataDisplay;
        "orcid-connect": OrcidConnect;
        "throughput-submit": ThroughputSubmit;
        "throughput-widget": ThroughputWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "annotations-display": LocalJSX.AnnotationsDisplay & JSXBase.HTMLAttributes<HTMLAnnotationsDisplayElement>;
            "data-display": LocalJSX.DataDisplay & JSXBase.HTMLAttributes<HTMLDataDisplayElement>;
            "orcid-connect": LocalJSX.OrcidConnect & JSXBase.HTMLAttributes<HTMLOrcidConnectElement>;
            "throughput-submit": LocalJSX.ThroughputSubmit & JSXBase.HTMLAttributes<HTMLThroughputSubmitElement>;
            "throughput-widget": LocalJSX.ThroughputWidget & JSXBase.HTMLAttributes<HTMLThroughputWidgetElement>;
        }
    }
}
